# Laboratório 3

Nota: Substitua os seus nomes e informações abaixo antes do envio da atividade. A atividade deve ser enviada no `Moodle` da disciplina, e o arquivo **DEVE** estar no formato `.ipynb`.

[Nome Aluno 1] / [NUSP Aluno 1] / [Vespertino/Noturno]

[Nome Aluno 2] / [NUSP Aluno 2] / [Vespertino/Noturno]


<p align="justify"> 1 -  Crie uma função que recebe 3 números como parâmetros e exiba a soma entre  eles. Depois, faça uma chamada à função.

In [1]:
def soma(n1, n2, n3):
    print(n1 + n2 + n3)


soma(2, 1, 3)

6


<p align="justify"> 2 - Crie uma função que receba 2 números. O primeiro é um valor e o segundo um percentual (ex. 10%). Retorne (return) o valor do primeiro número somado do aumento percentual do mesmo. Execute a função para ver se o resultado está correto.

In [2]:
def perc(n1, n2):
    return n1 + (n1 * n2 / 100)

print(perc(100,50))

150.0


<p align="justify"> 3 - Vá na documentação de strings do Python (<a href = https://docs.python.org/3/library/stdtypes.html?highlight=upper#string-methods> Link</a>). Com isso em mãos, crie uma função que recebe uma string como argumento e que deixa o primeiro caractere em maiúsculo. Chame a função ao final da célula.

In [3]:
def capitaliza(str1):
  return str1.capitalize()


capitaliza("josé amava lírios.")

'José amava lírios.'

<p align="justify"> 4 - Crie uma função que recebe uma lista de strings e as retorna totalmente em letras minúsculas.

In [4]:
# Com List Comprehension

def converter_para_lower(strings):
    strings_lower = [s.lower() for s in strings]
    return strings_lower

# Ou

def converter_para_lower2(strings):

  strings_lower = []

  for s in strings:
    strings_lower.append(s.lower())
  return strings_lower


# Lista de strings de exemplo
lista_strings = ["Python", "É", "Uma", "Linguagem", "De", "Programação"]

# Chamando a função e imprimindo o resultado 1
strings_lower1 = converter_para_lower(lista_strings)
print(strings_lower1)

# Chamando a função e imprimindo o resultado 2
strings_lower2 = converter_para_lower2(lista_strings)
print(strings_lower2)

['python', 'é', 'uma', 'linguagem', 'de', 'programação']
['python', 'é', 'uma', 'linguagem', 'de', 'programação']


<p align="justify"> 5 - Crie uma função que receba três listas como argumentos e as junte em um dicionário. A função deve retornar o dicionário final. Execute a função utilizando as três listas abaixo, apresentando o resultado final em um print. Lembre-se, cada elemento da lista deve estar associado ao seu equivalente dentro do dicionário (i.e. "Alice" com "Jonhson" com "alice@example.com"). Dica: você vai precisar da função <a href =https://docs.python.org/3/library/functions.html?highlight=zip#zip><i>zip</i></a> e revisar um pouco mais de <a href = https://docs.python.org/3/tutorial/datastructures.html?highlight=dictionaries#dictionaries> dicionários </a>.

In [5]:
# Listas de teste
primeiros_nomes = ["Alice", "Bob", "Carol", "David", "Eve"]
ultimos_nomes = ["Johnson", "Smith", "Williams", "Brown", "Davis"]
emails = ["alice@example.com", "bob@example.com", "carol@example.com", "david@example.com", "eve@example.com"]


def listas_em_dicionario(nomes, sobrenomes, emails):
    dicionario = {}
    for nome, sobrenome, email in zip(nomes, sobrenomes, emails):
        dicionario[nome] = {"sobrenome": sobrenome, "email": email}
    return dicionario



dicionario = listas_em_dicionario(primeiros_nomes,ultimos_nomes, emails)


# Exemplo de como imprimir os valores de um dicionário depois do resultado da função.

for nome, info in dicionario.items():
    print(f"Nome: {nome}, Sobrenome: {info['sobrenome']}, Email: {info['email']}")





Nome: Alice, Sobrenome: Johnson, Email: alice@example.com
Nome: Bob, Sobrenome: Smith, Email: bob@example.com
Nome: Carol, Sobrenome: Williams, Email: carol@example.com
Nome: David, Sobrenome: Brown, Email: david@example.com
Nome: Eve, Sobrenome: Davis, Email: eve@example.com


<p align="justify"> 6 - Abaixo você encontra uma lista com temperaturas em graus Celsius. Crie uma função anônima que converta cada temperatura para Fahrenheit. Dica: para conseguir realizar este exercício, você deve criar sua função <i>lambda</i>, dentro de uma função.

<p align="justify"> Fórmula: F = (C * 1,8) + 32.

In [6]:
Celsius = [35, 25, 17, 28.5]

# Modo conciso (tem exemplo parecido acima)
Fahrenheit = map(lambda x: (float(9)/5)*x + 32, Celsius)

# Definindo a função

def c_para_f(temps):
  fahrenheit = list(map(lambda x: (float(9)/5)*x + 32, temps))
  return fahrenheit


# Resultado do Modo extenso

resultado = c_para_f(Celsius)

print(list(resultado))

# Resultado do modo conciso
print(list(Fahrenheit))

# [95.0, 77.0, 62.6, 83.30000000000001]

[95.0, 77.0, 62.6, 83.30000000000001]
[95.0, 77.0, 62.6, 83.30000000000001]


<p align="justify"> 7 - Crie uma função que receba uma lista de números. Com essa lista, a função deve calcular média, moda, mediana e desvio padrão. Ao fim, deve imprimir cada um desses valores em linhas separadas. Não esqueça de conferir a <a href = https://docs.python.org/3/library/statistics.html?highlight=mean#statistics.mean> dica </a>.

In [7]:

import statistics as stat

lista_nums = [72,42,24,48,124,23]

def estatisticas(nums):
  media = stat.mean(nums)
  moda = stat.mode(nums)
  mediana = stat.median(nums)
  desvpad = stat.stdev(nums)

  print(f'A média da lista é: {media}')
  print(f'A moda da lista é: {moda}')
  print(f'A mediana da lista é: {mediana}')
  print(f'O desvio padrão da lista é: {desvpad}')


estatisticas(lista_nums)



A média da lista é: 55.5
A moda da lista é: 72
A mediana da lista é: 45.0
O desvio padrão da lista é: 38.082804518575045


<p align="justify"> 8 - Calculadora Simples: Crie uma calculadora simples com funções para realizar operações de adição, subtração, multiplicação e divisão. A função principal deve pedir ao usuário qual operação deseja realizar e, em seguida, solicitar os números para a operação.

In [8]:
def adicao(a, b):
    return a + b

def subtracao(a, b):
    return a - b

def multiplicacao(a, b):
    return a * b

def divisao(a, b):
    if b != 0:
        return a / b
    else:
        return "Não é possível dividir por zero."

def calculadora():
    print("Escolha a operação:")
    print("1. Adição")
    print("2. Subtração")
    print("3. Multiplicação")
    print("4. Divisão")
    print("===================")
    print(" ")

    escolha = input("Digite o número da operação desejada: ")

    num1 = float(input("Digite o primeiro número: "))
    num2 = float(input("Digite o segundo número: "))

    print(" ")
    print("###### Resultado ######")

    if escolha == "1":
        resultado = adicao(num1, num2)
    elif escolha == "2":
        resultado = subtracao(num1, num2)
    elif escolha == "3":
        resultado = multiplicacao(num1, num2)
    elif escolha == "4":
        resultado = divisao(num1, num2)
    else:
        resultado = "Operação inválida."

    print("Resultado:", resultado)

# Chamar a função calculadora para realizar uma operação
calculadora()

Escolha a operação:
1. Adição
2. Subtração
3. Multiplicação
4. Divisão
 
 
###### Resultado ######
Resultado: 10.0


<p align="justify"> Antes de ir aos próximos exercícios, explore a documentação própria do <i>Numpy</i> (<a href = https://numpy.org/doc/stable/reference/routines.html> Link</a>). Não esqueça de importar a biblicoteca também.

9 - Crie um array <i>NumPy</i> que contenha os primeiros 10 números pares. Imprima o array.

In [9]:
import numpy as np

In [10]:
numeros_pares = np.arange(0, 20, 2)
print(numeros_pares)

[ 0  2  4  6  8 10 12 14 16 18]


10 - Crie uma matriz identidade 4x4 usando <i>NumPy</i>. Imprima o array.

In [11]:
matriz_identidade = np.eye(4)
print(matriz_identidade)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


<p align="justify"> 11 - Utilizando um for loop, multiplique os valores da primeira lista pela segunda lista. Imprima o resultado final. Dica: Você pode precisar da função range() e len() vistas na aula anterior.

In [12]:
lista1 = [7,6,1,2,54,25]
lista2 = [1,2,3,4,5,6]

resultado = []

for x in range(0, len(lista1)):
  valor = lista1[x] * lista2[x]
  resultado.append(valor)


print(resultado)

[7, 12, 3, 8, 270, 150]


12 - Transforme as listas 1 e 2 em arrays e multiplique seus valores.

In [13]:
print(np.array(lista1) * np.array(lista2))


[  7  12   3   8 270 150]


13 - Pegue apenas os valores pares da seguinte lista utilizando um for loop.

In [14]:

lista = list(range(0,100))

pares = []

for i in lista:
  if i % 2 == 0:
    pares.append(i)
  else:
    pass

print(pares)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


14 - Transforme a lista do exercício 13 em um array e pegue os números pares.

In [15]:
array = np.array(lista)

pares = array[array % 2 == 0]

print(pares)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


<p align="justify"> 15 - Abaixo estão duas listas: uma com o nome de candidatos (inventados) e outra com valores <i>dummy</i> (ou binários) que informam se o candidato possui ou não twitter. Usando <i>NumPy</i> arrays, filtre os candidatos que <i>possuem</i> twitter.

In [16]:
import random

nomes = ["Alice", "Bob", "Carlos", "David", "Emily", "Fernanda", "Gabriel", "Hannah", "Isaac", "Julia",
         "Kevin", "Larissa", "Mateus", "Natalia", "Oliver", "Paula", "Quincy", "Renata", "Samuel", "Tatiana"]

twitter = [random.choice([0, 1]) for _ in range(20)]


nomes_array = np.array(nomes)
twitter_array = np.array(twitter)


candidatos_twitter = nomes_array[twitter_array == 1]

print(candidatos_twitter)

['Bob' 'Carlos' 'David' 'Emily' 'Gabriel' 'Larissa' 'Mateus' 'Natalia'
 'Oliver' 'Paula' 'Samuel']


16 - Escreva um programa NumPy para criar uma matriz 5x5 com valores aleatórios e calcule o exponencial de cada elemento. Confira a [dica](https://numpy.org/doc/stable/reference/routines.math.html#mathematical-functions) antes de iniciar o exercício.

In [17]:
nums = np.random.rand(5, 5)
print("Array original:")
print(nums)
exp_arr = np.exp(nums)
print("Exponencial do Array:")
print(exp_arr)

Array original:
[[0.02163099 0.90312743 0.57562367 0.96904119 0.97810938]
 [0.31230834 0.3612907  0.50599802 0.20897169 0.94457805]
 [0.48711114 0.66754923 0.09675176 0.18391454 0.46161729]
 [0.2798345  0.36576952 0.34164637 0.98395202 0.37539996]
 [0.85183356 0.33422892 0.48711237 0.17051976 0.13263956]]
Exponencial do Array:
[[1.02186663 2.46730738 1.77823921 2.63541639 2.65942352]
 [1.366576   1.43518061 1.65864004 1.2324101  2.57172802]
 [1.62760749 1.94945379 1.10158688 1.2019131  1.58663796]
 [1.32291085 1.44162294 1.40726256 2.67500706 1.45557347]
 [2.34394067 1.39686287 1.6276095  1.18592109 1.14183836]]


17 - Crie uma matriz (array) 3x2 e outra 2x3, sem utilizar o <i>random</i>, e multiplique-as.

Dica: Não dá para usar o operador "*".

In [18]:
matriz1 = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

matriz2 = np.array([[1,2,3],
                    [3,2,1]])

print(np.matmul(matriz1,matriz2))

[[ 7  6  5]
 [15 14 13]
 [23 22 21]]


18 - Transponha a segunda matriz do exercício 17 e refaça a operação proposta.

In [19]:
matriz2_T = np.transpose(matriz2)

print(matriz2_T)

print("Resultado: ")
print(matriz1 * matriz2_T)


[[1 3]
 [2 2]
 [3 1]]
Resultado: 
[[ 1  6]
 [ 6  8]
 [15  6]]


19 - Imprima o número 50 do seguinte array.

In [20]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

print(arr[1, 0])

50


20 - Crie uma matriz 3x3 de números e acesse o elemento da segunda linha e terceira coluna.

In [21]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
elemento = matriz[1, 2]
print(elemento)

6


21 - Crie uma matriz 4x4 de números e use fatiamento para obter uma submatriz 2x2 da parte superior esquerda.

In [22]:
matriz = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

submatriz = matriz[:2, :2]
print(submatriz)

[[1 2]
 [5 6]]


<p align="justify"> 22 - Crie uma função que recebe um array de strings que contém os usuários de twitter de deputados federais, remova o prefixo "@" e deixe tudo minúsculo. Depois, a aplique na <i>lista_twitters</i>.

Confira a [dica](https://numpy.org/doc/stable/reference/routines.char.html).

In [23]:

# Lista de nomes de usuário no twitter
lista_twitters = nomes_com_arroba = ["@Ana", "@Pedro", "@Isabel", "@João",
                                     "@Mariana", "@Rafael", "@Beatriz", "@Lucas",
                                     "@Carolina", "@Gustavo", "@Lívia", "@André",
                                     "@Júlia", "@Matheus", "@Laura", "@Gabriel",''
                                     "@Amanda", "@Daniel", "@Clara", "@Felipe"]

array_twitters = lista_twitters

def limpa_twitters(array):

  array = np.char.replace(array, '@', '')
  array = np.char.lower(array)
  return array



resultado = limpa_twitters(array_twitters)

print(resultado)


['ana' 'pedro' 'isabel' 'joão' 'mariana' 'rafael' 'beatriz' 'lucas'
 'carolina' 'gustavo' 'lívia' 'andré' 'júlia' 'matheus' 'laura' 'gabriel'
 'amanda' 'daniel' 'clara' 'felipe']
